### ISSUE TITLE
Missing dependency ?

### ISSUE THREAD

**Issue by pbaisla** [pakhandi/Contest_Notifier#4]
So I installed all the dependencies mentioned in the README (pytz, tk, icalendar) but it looks like something is still missing.

```
ini.py:185: SyntaxWarning: name 'time1' is assigned to before global declaration
  global time1
Traceback (most recent call last):
  File "ini.py", line 21, in <module>
    from gi.repository import Gtk as gtk
ImportError: No module named gi.repository
```

**Comment by pakhandi-zz** [comment]
Are you using Python-3 ?

**Comment by pbaisla** [comment]
Tried with both python2 and python3. The output above is of python2.

**Comment by pakhandi-zz** [comment]
Okay. Will add the installation instructions for this module too. Thanks for raising the issue :) . 
<b>sudo apt-get install python-gi</b> should fix this issue.

**Comment by pbaisla** [comment]
Installing gi doesn't help.

```
ini.py:185: SyntaxWarning: name 'time1' is assigned to before global declaration
  global time1
Traceback (most recent call last):
  File "ini.py", line 21, in <module>
    from gi.repository import Gtk as gtk
ImportError: No module named repository
```

BTW, should I be using python2 or python3?

**Comment by pakhandi-zz** [comment]
The program has been tested on Python-2.7.9

**Comment by pakhandi-zz** [comment]
Can you tell me if installing <b>python3-gi</b> helps?

**Comment by pbaisla** [comment]
Using python3 has some other problems (like different modules)

BTW are you sure `gi` is what is required?
Because it doesn't seem right.
https://pypi.python.org/pypi/gi/

**Comment by pakhandi-zz** [comment]
For Arch Linux I found this thread : https://bbs.archlinux.org/viewtopic.php?id=203480
Maybe some issue with python-gobject

**Comment by pbaisla** [comment]
Looks like `gobject` was what was required but it's still not quite working yet.

```
ini.py:185: SyntaxWarning: name 'time1' is assigned to before global declaration
  global time1
ini.py:21: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as gtk
ini.py:22: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify as notify
Traceback (most recent call last):
  File "ini.py", line 23, in <module>
    from gi.repository import AppIndicator3 as appindicator
ImportError: cannot import name AppIndicator3
```

Even after removing the warnings I get the same error above.

**Comment by pakhandi-zz** [comment]
I'll see to it.
Thanks again for raising the issue. :)
